### ISSUE TITLE
Merge with kopa-app/model?

### ISSUE THREAD

**Issue by der-On** [StephanHoyer/hedy#1]
Before starting again from scratch, could we try to merge with [kopa-app/model](https://github.com/kopa-app/model) including a nice roadmap, issue lifecycles and code rewievs?

**Comment by StephanHoyer** [comment]
My ides of lifecycle is currenlty this:

```
var store = fnORM(runQuery);

function afterSave(user, query) {
  // ...
  return whateverYouWantAsResolveValue;
}

function beforeSave(query) {
  // ...
  return user;
}

var baseQuery = store('user')

var lifeCycleQuery = baseQuery.beforeSave(fn).afterSave(afterSave);
```

Even multiple handlers are possible.

**Comment by der-On** [comment]
Sorry I meant "issue" lifecycles not model lifecycles. And with that I meant, that we do issue reviews, assignments etc. ;)

**Comment by StephanHoyer** [comment]
Ok,

yeah, let's do this :)
